name: "fetch-kanpo-action"
description: "官報の更新がないかをチェックする GitHub Actionです"
author: "testkun08080"

branding:
  icon: "cpu"
  color: "blue"

inputs:
  dlpdf:
    description: "PDFをダウンロードするか"
    required: false
    default: "false"
  date:
    description: "対象日付 (例: 2025-07-03), 指定しない場合は当日の日付を使用"
    required: false

outputs:
  kanpou_found:
    description: '官報が見つかったかどうか'
  pdf_infos:
    description: 'PDFの情報リスト'

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--dlpdf"
    - "${{ inputs.dlpdf }}"
    - "--date"
    - "${{ inputs.date }}"