[project]
name = "fetch-kanpo-action"
version = "0.1.0"
description = "Fetch kanpo page via GitHub Action"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.4",
]
